# Generated by Django 5.0.4 on 2026-06-07 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('prompt_gen', 'Prompt Generator'), ('email_gen', 'Email Generator'), ('linkedin_post', 'LinkedIn Post'), ('cover_letter', 'Cover Letter'), ('resume_summary', 'Resume Summary'), ('sql_gen', 'SQL Generator'), ('regex_gen', 'Regex Generator'), ('api_docs', 'API Docs Generator'), ('meeting_notes', 'Meeting Notes')], db_index=True, max_length=20)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_preview', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'AI Tool Request',
                'verbose_name_plural': 'AI Tool Requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessToolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('invoice', 'Invoice Generator'), ('gst', 'GST/VAT Calculator'), ('margin', 'Profit Margin'), ('markup', 'Markup Calculator'), ('rate', 'Freelance Rate'), ('payroll', 'Payroll Calculator')], db_index=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Business Tool Log',
                'verbose_name_plural': 'Business Tool Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevToolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('json_format', 'JSON Formatter'), ('json_validate', 'JSON Validator'), ('json_minify', 'JSON Minifier'), ('text_diff', 'Text Diff'), ('yaml_format', 'YAML Formatter'), ('base64_encode', 'Base64 Encode'), ('base64_decode', 'Base64 Decode'), ('url_encode', 'URL Encode'), ('url_decode', 'URL Decode'), ('jwt_decode', 'JWT Decode'), ('uuid_generate', 'UUID Generate'), ('hash_sha256', 'SHA-256 Hash'), ('hash_sha512', 'SHA-512 Hash'), ('hmac_generate', 'HMAC Generate'), ('regex_test', 'Regex Test')], db_index=True, max_length=20)),
                ('input_size', models.IntegerField(blank=True, null=True)),
                ('output_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dev Tool Log',
                'verbose_name_plural': 'Dev Tool Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileToolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('image_convert', 'Image Converter'), ('pdf_merge', 'PDF Merger'), ('pdf_minify', 'PDF Compressor')], db_index=True, max_length=20)),
                ('file_count', models.IntegerField(default=1)),
                ('input_size', models.IntegerField(blank=True, null=True)),
                ('output_size', models.IntegerField(blank=True, null=True)),
                ('savings_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Tool Log',
                'verbose_name_plural': 'File Tool Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('fire', 'FIRE Calculator'), ('coast_fire', 'Coast FIRE'), ('fat_fire', 'Fat FIRE'), ('barista_fire', 'Barista FIRE'), ('windfall', 'Windfall Impact'), ('purchase', 'Purchase Impact'), ('compound', 'Compound Interest'), ('loan', 'Loan Payment'), ('mortgage', '15v30 Mortgage'), ('portfolio', 'Portfolio Rebalance'), ('rental', 'Rental Property'), ('house_hack', 'House Hacking'), ('cap_rate', 'Cap Rate'), ('cash_on_cash', 'Cash-on-Cash'), ('savings_rate', 'Savings Rate'), ('emergency', 'Emergency Fund'), ('hsa', 'HSA Growth'), ('inflation', 'Inflation Calc'), ('upwork_fee', 'Upwork Fee'), ('ev_savings', 'EV Savings'), ('sip', 'SIP Calculator'), ('retirement', 'Retirement Calc'), ('rrsp', 'RRSP Contribution'), ('tfsa', 'TFSA Growth'), ('dividend', 'Dividend Yield'), ('currency', 'Currency Converter')], db_index=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Finance Calculation',
                'verbose_name_plural': 'Finance Calculations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IP Cache Entry',
            },
        ),
        migrations.CreateModel(
            name='IPLookupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('myip', 'My IP'), ('iplookup', 'IP Lookup'), ('hostname', 'Hostname Lookup'), ('whois', 'WHOIS'), ('blacklist', 'Blacklist Check'), ('portscan', 'Port Scanner'), ('traceroute', 'Traceroute'), ('dns', 'DNS Lookup'), ('useragent', 'User Agent'), ('speedtest', 'Speed Test'), ('mxrecord', 'MX Record'), ('spf', 'SPF Record'), ('ssl', 'SSL Checker'), ('headers', 'HTTP Headers')], db_index=True, max_length=20)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('result_cached', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IP Tool Log',
                'verbose_name_plural': 'IP Tool Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextToolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('word_count', 'Word Counter'), ('case_convert', 'Case Converter'), ('dedupe', 'Remove Duplicates'), ('lorem_ipsum', 'Lorem Ipsum'), ('markdown', 'Markdown Preview'), ('html_encode', 'HTML Encoder'), ('html_decode', 'HTML Decoder'), ('html_to_md', 'HTML to Markdown')], db_index=True, max_length=20)),
                ('input_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text Tool Log',
                'verbose_name_plural': 'Text Tool Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tool_name', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('total_uses', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tool Analytics',
                'ordering': ['-date', '-total_uses'],
                'unique_together': {('date', 'tool_name')},
            },
        ),
    ]
