# Generated by Django 5.0.4 on 2026-06-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_aitoolrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitoolrequest',
            name='tool',
            field=models.CharField(choices=[('prompt_gen', 'Prompt Generator'), ('email_gen', 'Email Generator'), ('linkedin_post', 'LinkedIn Post'), ('cover_letter', 'Cover Letter'), ('resume_summary', 'Resume Summary'), ('sql_gen', 'SQL Generator'), ('regex_gen', 'Regex Generator'), ('api_docs', 'API Docs Generator'), ('meeting_notes', 'Meeting Notes'), ('upwork_proposal', 'Upwork Proposal Generator'), ('recruiter_reply', 'LinkedIn Recruiter Reply'), ('job_matcher', 'Job Description Matcher'), ('cron_gen', 'Cron Generator'), ('api_tester', 'API Tester')], db_index=True, max_length=20),
        ),
    ]
