# Generated by Django 5.0.4 on 2026-08-06 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('raw_text', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('achievements', models.JSONField(default=list)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('career_goal', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
