# Generated by Django 5.0.4 on 2026-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_authnet_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('no_ads', 'No Ads'), ('ai_tools', 'AI Tools'), ('form_tools', 'Form Tools'), ('form_ai', 'Form Tools + AI Tools'), ('no_ads_form_ai', 'No Ads + Form Tools + AI Tools'), ('api_full', 'API Access (Full Bundle)')], db_index=True, max_length=20),
        ),
    ]
