# Generated by Django 5.0.4 on 2026-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_form_tools',
            field=models.BooleanField(default=False),
        ),
    ]
