# Generated by Django 5.0.4 on 2026-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_plan_allows_form_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
