# Generated by Django 5.0.4 on 2026-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_is_trial_subscription_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_chrome_extension',
            field=models.BooleanField(default=False),
        ),
    ]
