# Generated by Django 5.0.4 on 2026-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_allows_chrome_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('ai_tools', 'AI Tool'), ('ai_tools_plus', 'AI + Chrome Extension'), ('ai_premium', 'AI Premium')], db_index=True, max_length=20),
        ),
    ]
